"""priority_rules.py - Job-selection priority rules for baseline scheduling
heuristics.

Each rule is a key function key(base_env, job) -> comparable; the baseline
picks the job with the MINIMUM key among jobs that have >=1 feasible machine
this step (registry.py breaks ties by ascending job index for determinism
and to exactly reproduce the original EDF/SPT/LST behaviour in
eval_rl_agent.py, which iterated action ids in ascending job*num_machines+
machine order). See Future/research/2026-08-28-classical-heuristic-baselines.md
for full citation grounding; short form below.
"""


def edf_key(base_env, job):
    """Earliest Deadline First -- classical scheduling priority rule (see
    e.g. Pinedo, "Scheduling: Theory, Algorithms, and Systems")."""
    return base_env.job_deadlines[job]


def spt_key(base_env, job):
    """Shortest Processing Time."""
    return base_env.job_durations[job]


def lst_key(base_env, job):
    """Least Slack Time: deadline - duration - now."""
    return base_env.job_deadlines[job] - base_env.job_durations[job] - base_env.time


def fcfs_key(base_env, job):
    """First-Come-First-Served. Every job in this environment is available
    at t=0 (SchedulingEnv models static, deterministic jobs -- see its
    module docstring), so "arrival order" reduces to job index. Named as a
    baseline in the project's own literature review (NotesForAI's RA
    taxonomy, p.5)."""
    return job


def lpt_key(base_env, job):
    """Longest Processing Time. Grounded in Graham (1969), "Bounds on
    Multiprocessing Timing Anomalies" (SIAM J. Applied Math), which proves
    LPT's (4/3 - 1/(3m)) makespan approximation bound on identical parallel
    machines -- the classical justification for preferring long jobs first.
    Implemented as the negation of the SPT key since every rule here is
    selected by minimum key."""
    return -base_env.job_durations[job]


def wspt_key(base_env, job):
    """Weighted Shortest Processing Time (Smith's rule -- W.E. Smith, 1956,
    "Various optimizers for single-stage production", Naval Research
    Logistics Quarterly): ratio duration/weight, proven optimal for
    minimizing total weighted completion time on a single machine.
    NOTE (honesty check, per CLAUDE.md): every instance generated by
    Code/env/env_config.py::generate_env_config sets job_weights uniformly
    to 1, so WSPT is numerically identical to SPT until an instance with
    non-uniform weights is actually evaluated -- report this plainly rather
    than presenting WSPT as empirically distinct when it cannot be, given
    current instance generation."""
    return base_env.job_durations[job] / max(base_env.job_weights[job], 1e-8)


PRIORITY_RULES = {
    "EDF": edf_key,
    "SPT": spt_key,
    "LST": lst_key,
    "FCFS": fcfs_key,
    "LPT": lpt_key,
    "WSPT": wspt_key,
}
