"""priority_rules.py - Job-selection priority rules for baseline scheduling
heuristics.

Each rule is a key function key(base_env, job) -> comparable; the baseline
picks the job with the MINIMUM key among jobs that have >=1 feasible machine
this step (registry.py breaks ties by ascending job index for determinism
and to exactly reproduce the original EDF/SPT/LST behaviour in
eval_rl_agent.py, which iterated action ids in ascending job*num_machines+
machine order). See Future/research/2026-08-28-classical-heuristic-baselines.md
for full citation grounding; short form below.
"""
import math


def edf_key(base_env, job):
    """Earliest Deadline First -- classical scheduling priority rule (see
    e.g. Pinedo, "Scheduling: Theory, Algorithms, and Systems")."""
    return base_env.job_deadlines[job]


def spt_key(base_env, job):
    """Shortest Processing Time."""
    return base_env.job_durations[job]


def lst_key(base_env, job):
    """Least Slack Time: deadline - duration - now."""
    return base_env.job_deadlines[job] - base_env.job_durations[job] - base_env.time


def fcfs_key(base_env, job):
    """First-Come-First-Served.

    Online case (OnlineSchedulingEnv, has .arrival_times): "first come" means
    actual arrival order, tau_j -- ties (same-tick arrivals) fall back to job
    index for determinism, matching every other rule's tie-breaking here.

    Offline case (plain SchedulingEnv, no .arrival_times): every job is
    available at t=0 (see its module docstring), so "arrival order" reduces
    to job index -- unchanged from the original behaviour. Named as a
    baseline in the project's own literature review (NotesForAI's RA
    taxonomy, p.5).

    registry.py already wraps every key function's return value with `job`
    as a secondary tie-break (key=lambda j: (priority_key(base_env, j), j)),
    so same-tick arrivals need no special handling here -- a plain scalar
    return, matching every other rule's convention, is sufficient."""
    arrival_times = getattr(base_env, "arrival_times", None)
    if arrival_times is not None:
        return arrival_times[job]
    return job


def lpt_key(base_env, job):
    """Longest Processing Time. Grounded in Graham (1969), "Bounds on
    Multiprocessing Timing Anomalies" (SIAM J. Applied Math), which proves
    LPT's (4/3 - 1/(3m)) makespan approximation bound on identical parallel
    machines -- the classical justification for preferring long jobs first.
    Implemented as the negation of the SPT key since every rule here is
    selected by minimum key."""
    return -base_env.job_durations[job]


def wspt_key(base_env, job):
    """Weighted Shortest Processing Time (Smith's rule -- W.E. Smith, 1956,
    "Various optimizers for single-stage production", Naval Research
    Logistics Quarterly): ratio duration/weight, proven optimal for
    minimizing total weighted completion time on a single machine.
    NOTE (honesty check, per CLAUDE.md): every instance generated by
    Code/env/env_config.py::generate_env_config sets job_weights uniformly
    to 1, so WSPT is numerically identical to SPT until an instance with
    non-uniform weights is actually evaluated -- report this plainly rather
    than presenting WSPT as empirically distinct when it cannot be, given
    current instance generation."""
    return base_env.job_durations[job] / max(base_env.job_weights[job], 1e-8)


def _atc_mean_p(base_env):
    """mean_p for the ATC formula -- see atc_priority()'s docstring for what
    it means and why it's restricted to known_jobs online. Extracted as its
    own function (2026-09-21, S2W9, from Future/research/2026-09-20-
    optimisation-and-efficiency-critique.md Section 1.5) so callers that
    invoke atc_priority()/atc_key() once per candidate job in a single sort
    (Code/baselines/registry.py's choose()) can compute this ONCE (it
    depends only on base_env's state, not on which job is being scored) and
    pass it in, instead of each of the J calls recomputing the identical
    O(num_jobs) sum from scratch -- O(J*num_jobs) collapsing to O(num_jobs)
    for one ranking. Safe because nothing mutates base_env's state between
    calls within a single sort (verified before this change, not assumed)."""
    revealed = getattr(base_env, "revealed_jobs", None)
    known_jobs = revealed if revealed else range(len(base_env.job_durations))
    return max(1e-8, sum(base_env.job_durations[j] for j in known_jobs) / len(known_jobs))


def atc_priority(base_env, job, k: float = 2.0, mean_p: float = None):
    """Raw Apparent Tardiness Cost priority I_j(t) (Vepsalainen & Morton,
    1987, "Priority Rules for Job Shops with Weighted Tardiness Costs,"
    Management Science 33(8)):

        I_j(t) = (w_j / p_j) * exp(-max(d_j - p_j - t, 0) / (k * mean_p))

    A smooth interpolation between Smith's rule (w_j/p_j, WSPT -- optimal for
    weighted completion time with no deadlines) and pure urgency: priority is
    near 0 while a job has ample slack, and ramps up to the full w_j/p_j
    value as slack shrinks toward 0, saturating there rather than growing
    further once a job is already at risk. Standard heuristic for weighted-
    tardiness objectives, matching this project's own lambda_2*w_j*T_j
    reward term. k=2.0 is a commonly-used literature default (Vepsalainen &
    Morton's own tuning experiments), not a value re-derived or re-tuned for
    this project's instance distribution -- flagged per CLAUDE.md's rule
    that untested constants must say so.

    Online-adapted: mean_p is computed over only the jobs currently known to
    have arrived (getattr(base_env, "revealed_jobs", None)), not the full
    job array -- keeping this baseline causally restricted to information
    actually available at decision time (the online-case plan's "online-
    adapted classical heuristics ... restricted to currently-arrived jobs").
    Falls back to every job for the offline case (plain SchedulingEnv, no
    .revealed_jobs), where full self-knowledge is legitimate.

    HIGHER means more urgent/valuable to schedule now -- the usual ATC
    convention. Factored out from atc_key (below), which negates this to fit
    every other priority rule's "minimum key wins" convention, so this
    un-negated form has one definition used two ways: as a baseline's
    ranking key (via atc_key) and directly as an RL observation feature
    (Code/env/priority_only_gym_wrapper.py's Option 3, the ATC-primed
    priority-learning variant of the 2026-09-17 action-space-reduction work)
    -- rather than duplicating the formula for the second use.

    mean_p: optional precomputed _atc_mean_p(base_env) -- pass this when
    scoring multiple jobs against the SAME base_env state in one ranking
    (e.g. registry.py's choose()) to avoid recomputing the identical
    O(num_jobs) sum once per candidate job. None (default) computes it
    internally, preserving the original single-call behaviour exactly.
    """
    if mean_p is None:
        mean_p = _atc_mean_p(base_env)

    p_j = base_env.job_durations[job]
    w_j = base_env.job_weights[job]
    slack = base_env.job_deadlines[job] - p_j - base_env.time
    urgency = math.exp(-max(slack, 0.0) / (k * mean_p))
    return (w_j / max(p_j, 1e-8)) * urgency


def atc_key(base_env, job, k: float = 2.0, mean_p: float = None):
    """Apparent Tardiness Cost priority rule -- see atc_priority() for the
    formula and citation. Negated so that HIGHER priority (the usual ATC
    convention: maximize I_j) becomes a SMALLER key, matching every other
    rule here's "minimum key wins" convention (see lpt_key's identical
    negation).

    NOT the state-dependent-tuned variant of Min & Kim (2022, "State-
    Dependent Parameter Tuning of the Apparent Tardiness Cost Dispatching
    Rule Using Deep Reinforcement Learning," IEEE Access 10) -- that tunes k
    itself via a DDPG agent conditioned on raw job data, a genuinely separate
    small RL-training sub-project, not implemented here. This is the
    original, fixed-k ATC rule; the state-dependent extension remains future
    work.

    mean_p: see atc_priority()'s matching parameter -- forwarded unchanged.
    """
    return -atc_priority(base_env, job, k, mean_p)


PRIORITY_RULES = {
    "EDF": edf_key,
    "SPT": spt_key,
    "LST": lst_key,
    "FCFS": fcfs_key,
    "LPT": lpt_key,
    "WSPT": wspt_key,
    "ATC": atc_key,
}
