"""train_optimized.py - Train RL agent using Optuna-optimized hyperparameters

This script loads the best hyperparameters found by Optuna and trains
a full-scale model with curriculum learning.
"""

import os
import json
import argparse
from pathlib import Path
import numpy as np
import torch
import torch.nn as nn
from stable_baselines3.common.monitor import Monitor
from sb3_contrib import MaskablePPO
from sb3_contrib.common.wrappers import ActionMasker

from Code.env.scheduling_env import SchedulingEnv
from Code.env.gym_scheduling_wrapper import GymSchedulingEnv
from Code.env.env_config import generate_env_config
from Code.utils.plotting_utils import make_run_dir, LiveTrainingPlotter
from Code.utils.paths import LOG_DIR, MODELS_DIR, PLOTS_DIR, OPTUNA_RESULTS_DIR, ENV_CONFIG_PATH, ensure_rl_training_dirs
from Code.utils.results_log import archive_checkpoint_files


def mask_fn(env: GymSchedulingEnv):
    """Action mask function for ActionMasker"""
    return env.get_action_mask()


# Experiment 2 (randomized-instance generalization): training draws per-episode
# job-set seeds from [1, RANDOM_INSTANCE_SEED_CEILING). Held-out evaluation seeds
# (Code/evaluation/eval_rl_agent.py's --randomized-eval) live at/above this
# ceiling, so by construction no training seed can ever coincide with an eval
# seed -- no need to track/exclude a used-seed set at runtime.
RANDOM_INSTANCE_SEED_CEILING = 500_000


def make_random_instance_resampler(num_jobs: int, num_machines: int, horizon: int):
    """Returns a zero-arg callable that draws a fresh random job set (same
    num_jobs/num_machines/horizon every call, per GymSchedulingEnv.set_jobs()'s
    requirement) each time it's invoked -- passed as GymSchedulingEnv's
    job_resampler so every episode reset() gets a genuinely different instance
    instead of reusing the one fixed instance every prior result in this project
    trained/evaluated on. See Future/research/training-log.md's S2W5 entries and
    2026-08-09-pointer-network-action-head.md Section 9/10 for why this is the
    real test of the pointer network's generalization design claim.
    """
    def resample():
        seed = int(np.random.randint(1, RANDOM_INSTANCE_SEED_CEILING))
        return generate_env_config(seed=seed, num_jobs=num_jobs, num_machines=num_machines, horizon=horizon)
    return resample


def make_env(
    seed: int = 0,
    num_jobs=None,
    num_machines=None,
    horizon=None,
    max_jobs=None,
    lambda_1: float = 1.0,
    lambda_2: float = 1.0,
    lambda_3: float = 1.0,
    invalid_penalty: float = 5.0,
    idle_penalty: float = 0.5,
    use_potential_shaping: bool = False,
    shaping_gamma: float = 0.99,
    randomize_instances: bool = False,
):
    """Environment creation with tunable reward penalties.

    use_potential_shaping/shaping_gamma: Solution 3 (Ng, Harada, Russell 1999
    potential-based shaping, see SchedulingEnv._compute_potential()) -- off by
    default. shaping_gamma should match the RL algorithm's own gamma (passed
    explicitly by callers below, not left at this default) so the shaping
    term's policy-invariance guarantee holds under the same discounting the
    algorithm actually uses.

    randomize_instances: Experiment 2 -- if True, every episode reset() draws a
    fresh random job set (same num_jobs/num_machines/horizon as this call, per
    the curriculum stage) instead of reusing the single instance generated by
    `seed` below. `seed`/the initial config below still construct the env's
    *first* job set (needed to construct SchedulingEnv at all), but it gets
    immediately replaced on the first reset() once training starts.
    """

    config = generate_env_config(seed=seed)

    # Curriculum overrides
    if num_jobs is not None:
        config["job_durations"] = config["job_durations"][:num_jobs]
        config["job_resources"] = config["job_resources"][:num_jobs, :]
        config["job_deadlines"] = config["job_deadlines"][:num_jobs]
        config["job_weights"] = config["job_weights"][:num_jobs]
        config["num_jobs"] = num_jobs

    if num_machines is not None:
        config["num_machines"] = num_machines
        config["machine_capacity"] = config["machine_capacity"]

    if horizon is not None:
        config["horizon"] = horizon

    if max_jobs is not None:
        config["max_jobs"] = max_jobs

    # Save config for evaluation
    ensure_rl_training_dirs()
    np.savez(ENV_CONFIG_PATH, **config)

    # Create the base environment with tunable penalties
    base_env = SchedulingEnv(
        job_durations=config["job_durations"],
        job_resources=config["job_resources"],
        job_deadlines=config["job_deadlines"],
        job_weights=config["job_weights"],
        num_machines=config["num_machines"],
        machine_capacity=config["machine_capacity"],
        horizon=config["horizon"],
        lambda_1=lambda_1,
        lambda_2=lambda_2,
        lambda_3=lambda_3,
        invalid_penalty=invalid_penalty,
        idle_penalty=idle_penalty,
        use_potential_shaping=use_potential_shaping,
        shaping_gamma=shaping_gamma,
    )

    # Wrap in Gym + Masking. job_resampler is None (fixed-instance, previous
    # behaviour) unless randomize_instances=True -- see
    # make_random_instance_resampler() and GymSchedulingEnv.reset().
    job_resampler = (
        make_random_instance_resampler(config["num_jobs"], config["num_machines"], config["horizon"])
        if randomize_instances else None
    )
    gym_env = GymSchedulingEnv(base_env, max_jobs=max_jobs, job_resampler=job_resampler)
    masked_env = ActionMasker(gym_env, mask_fn)
    monitored_env = Monitor(masked_env)

    return monitored_env


def load_best_params(algorithm: str = "ppo", policy_type: str = "pointer", params_tag: str = None):
    """Load best hyperparameters from Optuna optimization.

    file_tag mirrors optuna_tune.py::run_optimization()'s output naming: A2C
    saves per-architecture files ("a2c_pointer_best_params.json",
    "a2c_flat_best_params.json"); PPO only has one architecture ("ppo_best_params.json").

    params_tag: optional suffix (e.g. "tardiness") to load an alternative params
    file produced by `optuna_tune.py --optimize-for tardiness`
    ("a2c_pointer_tardiness_best_params.json") instead of the default
    reward-tuned one, for comparing the two without overwriting either.
    """
    tag_suffix = f"_{params_tag}" if params_tag else ""
    file_tag = f"{algorithm}_{policy_type}{tag_suffix}" if algorithm == "a2c" else f"{algorithm}{tag_suffix}"
    best_params_file = OPTUNA_RESULTS_DIR / f"{file_tag}_best_params.json"

    if not os.path.exists(best_params_file):
        raise FileNotFoundError(
            f"Best parameters file not found: {best_params_file}\n"
            f"Please run optuna_tune.py first to optimize hyperparameters."
        )

    with open(best_params_file, "r") as f:
        params = json.load(f)

    print(f"\nLoaded best hyperparameters from: {best_params_file}")
    print("\nHyperparameters:")
    for key, value in params.items():
        print(f"  {key}: {value}")
    print()

    return params


def train_with_optimized_params(
    algorithm: str = "ppo",
    policy_type: str = "pointer",
    use_curriculum: bool = True,
    stage4_timesteps: int = 200_000,
    run_tag: str = None,
    params_tag: str = None,
    use_potential_shaping: bool = False,
    randomize_instances: bool = False,
    use_rcpo: bool = False,
    rcpo_alpha: float = 0.0,
    rcpo_lambda_lr: float = 0.01,
    rcpo_lambda_max: float = 50.0,
    rcpo_update_every: int = 5,
):
    """Train agent using optimized hyperparameters from Optuna.

    Args:
        algorithm: "ppo" or "a2c"
        policy_type: "pointer" or "flat" -- A2C only, ignored for PPO. Must match
            which architecture's best-params file to load AND which architecture
            to actually build (see the BUG FIX comment in the A2C branch below).
        use_curriculum: Whether to use curriculum learning
        stage4_timesteps: Timestep budget for the final curriculum stage
            (100 jobs, horizon=100). Overridable because the 2026-08-10
            training-log entry found the pointer architecture was still
            improving (not plateaued) at the default 200k -- see
            Future/research/training-log.md, S2W4 entry.
        run_tag: Label for this run's archived checkpoints (see
            Code/utils/results_log.py::archive_checkpoint_files). Defaults to
            "<algo>_<policy_type>_s4-<stage4_timesteps>" if not given. The
            canonical (non-archived) checkpoint at MODELS_DIR is still
            overwritten as before -- the archive is a separate, dated copy.
        params_tag: optional suffix (e.g. "tardiness") to train from an
            alternative Optuna params file produced by
            `optuna_tune.py --optimize-for tardiness`, and save to a
            correspondingly-suffixed checkpoint path so it doesn't overwrite
            the default reward-tuned model -- see load_best_params().
        use_potential_shaping: Experiment 4 (Solution 3, Ng/Harada/Russell 1999
            potential-based shaping) ablation flag. Deliberately kept
            orthogonal to params_tag -- this run still loads the *reward*-tuned
            params (params_tag=None) unless params_tag is also given, so the
            ablation isolates shaping as the only changed variable against the
            S2W4 baseline. shaping_gamma is set to this run's own `gamma`
            hyperparameter, not a separate default -- see make_env().
        randomize_instances: Experiment 2 -- train on a fresh random job set
            every episode (Code/training/train_optimized.py::
            make_random_instance_resampler()) instead of the single fixed
            seed=0 instance every prior run in this project used. NOTE: the
            Optuna hyperparameters loaded here were NOT re-tuned for this
            distribution (that re-tuning is a flagged follow-up, not done in
            this pass) -- results should be read with that caveat.
        use_rcpo: Experiment 5 (RCPO-style constrained optimization, A2C
            only -- see Code/policies/a2c_policy.py and
            Future/research/2026-08-21-rcpo-constrained-tardiness.md).
            Replaces the fixed lambda_2 tardiness weight with a Lagrange
            multiplier that adapts during training toward the constraint
            `E[C(tau)] <= rcpo_alpha`. Warm-started from this run's loaded
            `lambda_2` (params["lambda_2"]) rather than an arbitrary value.
        rcpo_alpha/rcpo_lambda_lr/rcpo_lambda_max/rcpo_update_every: see
            MaskableA2C's docstring for the grounding of each default.
    """
    if run_tag is None:
        run_tag = (
            f"{algorithm}_{policy_type}_s4-{stage4_timesteps}"
            + (f"_{params_tag}" if params_tag else "")
            + ("_shaped" if use_potential_shaping else "")
            + ("_randinst" if randomize_instances else "")
            + ("_rcpo" if use_rcpo else "")
        )

    if use_rcpo and algorithm != "a2c":
        raise ValueError(
            "use_rcpo=True is only supported for algorithm='a2c' -- RCPO+PPO "
            "integration is out of scope for Experiment 5, see "
            "Future/research/2026-08-21-rcpo-constrained-tardiness.md Section 5."
        )

    # Load best hyperparameters
    params = load_best_params(algorithm, policy_type=policy_type, params_tag=params_tag)

    # Setup directories. A2C paths are tagged with policy_type -- flat and
    # pointer checkpoints have different state_dict shapes and are not
    # interchangeable, so they must not overwrite each other. params_tag (if
    # given) is also appended, so a tardiness-tuned model doesn't overwrite the
    # default reward-tuned one at the same policy_type.
    TOTAL_TIMESTEPS = 500_000 if use_curriculum else 300_000
    path_suffix = (
        (f"_{params_tag}" if params_tag else "")
        + ("_shaped" if use_potential_shaping else "")
        + ("_randinst" if randomize_instances else "")
        + ("_rcpo" if use_rcpo else "")
    )
    PPO_MODEL_PATH = MODELS_DIR / f"ppo_scheduling_optimized{path_suffix}"
    A2C_MODEL_PATH = MODELS_DIR / f"a2c_{policy_type}_scheduling_optimized{path_suffix}.pt"

    ensure_rl_training_dirs()

    # Live plotter
    plot_run_dir = make_run_dir(str(PLOTS_DIR / "training"), f"{algorithm}_optimized")
    plotter = LiveTrainingPlotter(save_dir=plot_run_dir)

    # Extract reward penalties from params
    lambda_1 = params.get("lambda_1", 1.0)
    lambda_2 = params.get("lambda_2", 1.0)
    lambda_3 = params.get("lambda_3", 1.0)
    # shaping_gamma matches this run's own discount factor (see make_env()'s
    # docstring on why that matters for the policy-invariance guarantee to hold).
    shaping_gamma = params.get("gamma", 0.99)
    idle_penalty = params.get("idle_penalty", 0.5)
    invalid_penalty = params.get("invalid_penalty", 5.0)

    # BUG FIX (this session): the Greek-subscript characters here crash with
    # UnicodeEncodeError whenever stdout isn't a UTF-8-capable console --
    # notably when piped/redirected on Windows, where the default codepage is
    # cp1252. Plain ASCII avoids depending on the caller's console encoding.
    print(f"\nReward penalties:")
    print(f"  Machine activation (lambda_1): {lambda_1}")
    print(f"  Tardiness (lambda_2): {lambda_2}")
    print(f"  Hotspot (lambda_3): {lambda_3}")
    print(f"  Idle penalty: {idle_penalty}")
    print(f"  Invalid penalty: {invalid_penalty}\n")

    # ==================== PPO TRAINING ====================
    if algorithm == "ppo":
        # Build network architecture
        layer_size = params.get("layer_size", 256)
        n_layers = params.get("n_layers", 2)
        activation = params.get("activation", "tanh")

        if n_layers == 2:
            net_arch = dict(pi=[layer_size, layer_size], vf=[layer_size, layer_size])
        else:
            net_arch = dict(
                pi=[layer_size, layer_size, layer_size],
                vf=[layer_size, layer_size, layer_size]
            )

        activation_fn = nn.Tanh if activation == "tanh" else nn.ReLU

        policy_kwargs = dict(
            net_arch=net_arch,
            activation_fn=activation_fn,
        )

        # Curriculum or single-stage training
        if use_curriculum:
            MAX_JOBS = 100
            curriculum = [
                {"horizon": 20,  "num_jobs": 15,  "timesteps": 50_000},
                {"horizon": 40,  "num_jobs": 30,  "timesteps": 100_000},
                {"horizon": 60,  "num_jobs": 60,  "timesteps": 150_000},
                {"horizon": 100, "num_jobs": 100, "timesteps": stage4_timesteps},
            ]
        else:
            MAX_JOBS = 100
            curriculum = [
                {"horizon": 100, "num_jobs": 100, "timesteps": TOTAL_TIMESTEPS},
            ]

        # Create first environment
        first_env = make_env(
            seed=0,
            horizon=curriculum[0]["horizon"],
            num_jobs=curriculum[0]["num_jobs"],
            max_jobs=MAX_JOBS,
            lambda_1=lambda_1,
            lambda_2=lambda_2,
            lambda_3=lambda_3,
            idle_penalty=idle_penalty,
            invalid_penalty=invalid_penalty,
            use_potential_shaping=use_potential_shaping,
            shaping_gamma=shaping_gamma,
            randomize_instances=randomize_instances,
        )

        # Create PPO model with optimized hyperparameters
        model = MaskablePPO(
            "MlpPolicy",
            first_env,
            verbose=1,
            tensorboard_log=str(LOG_DIR),
            learning_rate=params.get("learning_rate", 3e-4),
            n_steps=params.get("n_steps", 2048),
            batch_size=params.get("batch_size", 256),
            n_epochs=params.get("n_epochs", 4),
            gamma=params.get("gamma", 0.99),
            gae_lambda=params.get("gae_lambda", 0.95),
            ent_coef=params.get("ent_coef", 0.05),
            clip_range=params.get("clip_range", 0.2),
            vf_coef=params.get("vf_coef", 0.5),
            max_grad_norm=params.get("max_grad_norm", 0.5),
            seed=0,
            policy_kwargs=policy_kwargs,
        )

        print(f"\n{'='*80}")
        print(f"Training PPO with optimized hyperparameters")
        print(f"Curriculum stages: {len(curriculum)}")
        print(f"Total timesteps: {sum(stage['timesteps'] for stage in curriculum)}")
        print(f"{'='*80}\n")

        # Curriculum training loop
        stage_ckpts = []
        for i, stage in enumerate(curriculum):
            print(f"\n--- Stage {i+1}/{len(curriculum)} ---")
            print(f"  Horizon: {stage['horizon']}, Jobs: {stage['num_jobs']}, Timesteps: {stage['timesteps']}")

            env = make_env(
                seed=0,
                horizon=stage["horizon"],
                num_jobs=stage["num_jobs"],
                max_jobs=MAX_JOBS,
                lambda_1=lambda_1,
                lambda_2=lambda_2,
                lambda_3=lambda_3,
                idle_penalty=idle_penalty,
                invalid_penalty=invalid_penalty,
                use_potential_shaping=use_potential_shaping,
                shaping_gamma=shaping_gamma,
                randomize_instances=randomize_instances,
            )

            model.set_env(env)

            model.learn(
                total_timesteps=stage["timesteps"],
                tb_log_name="ppo_scheduling_optimized",
                progress_bar=True,
                callback=plotter,
                reset_num_timesteps=False,
            )

            # Per-stage checkpoint -- see the matching comment in
            # train_rl_agent.py for rationale (diagnosability without rerunning
            # the whole curriculum).
            stage_ckpt = MODELS_DIR / f"ppo_optimized_stage{i}_h{stage['horizon']}{path_suffix}"
            model.save(stage_ckpt)
            print(f"  Saved stage checkpoint: {stage_ckpt}")
            stage_ckpts.append(Path(str(stage_ckpt) + ".zip"))  # SB3 appends .zip itself

        # Save PPO model
        model.save(PPO_MODEL_PATH)
        print(f"\nPPO training complete. Model saved to: {PPO_MODEL_PATH}\n")

        # Archive this run's checkpoints under a dated/tagged folder so the
        # next run overwriting PPO_MODEL_PATH doesn't destroy this one -- see
        # Code/utils/results_log.py.
        archive_dir = archive_checkpoint_files(
            [Path(str(PPO_MODEL_PATH) + ".zip"), *stage_ckpts, ENV_CONFIG_PATH],
            tag=run_tag,
        )
        print(f"Archived checkpoints to: {archive_dir}\n")

    # ==================== A2C TRAINING ====================
    else:
        from Code.policies.a2c_policy import MaskableA2C

        # For A2C, we need to modify the class to accept hyperparameters
        # This is similar to what we did in optuna_tune.py

        if use_curriculum:
            MAX_JOBS = 100
            curriculum = [
                {"horizon": 20,  "num_jobs": 15,  "timesteps": 50_000},
                {"horizon": 40,  "num_jobs": 30,  "timesteps": 100_000},
                {"horizon": 60,  "num_jobs": 60,  "timesteps": 150_000},
                {"horizon": 100, "num_jobs": 100, "timesteps": stage4_timesteps},
            ]
        else:
            MAX_JOBS = 100
            curriculum = [
                {"horizon": 100, "num_jobs": 100, "timesteps": TOTAL_TIMESTEPS},
            ]

        # Create first environment
        first_env = make_env(
            seed=0,
            horizon=curriculum[0]["horizon"],
            num_jobs=curriculum[0]["num_jobs"],
            max_jobs=MAX_JOBS,
            lambda_1=lambda_1,
            lambda_2=lambda_2,
            lambda_3=lambda_3,
            idle_penalty=idle_penalty,
            invalid_penalty=invalid_penalty,
            use_potential_shaping=use_potential_shaping,
            shaping_gamma=shaping_gamma,
            randomize_instances=randomize_instances,
        )

        # Create A2C agent.
        # BUG FIX (this session): this used to always call
        # MaskableA2C(first_env, device="cpu") with no policy_type/policy_kwargs,
        # so it silently ignored policy_type entirely (always built the default
        # "pointer" architecture with PointerActorCritic's hardcoded
        # embed_dim=128/hidden=64) and any embed_dim/hidden Optuna actually found
        # were never applied. Now explicitly threads both through.
        policy_kwargs = (
            dict(embed_dim=params.get("embed_dim", 128), hidden=params.get("hidden", 64))
            if policy_type == "pointer" else None
        )
        rcpo_kwargs = (
            dict(
                use_rcpo=True,
                rcpo_alpha=rcpo_alpha,
                rcpo_lambda_init=lambda_2,
                rcpo_lambda_lr=rcpo_lambda_lr,
                rcpo_lambda_max=rcpo_lambda_max,
                rcpo_update_every_episodes=rcpo_update_every,
            )
            if use_rcpo else {}
        )
        agent = MaskableA2C(
            first_env, device="cpu", policy_type=policy_type, policy_kwargs=policy_kwargs, **rcpo_kwargs
        )
        if use_rcpo:
            print(
                f"RCPO enabled: lambda_2 warm-started at {lambda_2} (this run's tuned "
                f"value), alpha={rcpo_alpha}, lambda_lr={rcpo_lambda_lr}, "
                f"lambda_max={rcpo_lambda_max}, update_every={rcpo_update_every} episodes\n"
            )

        # Override hyperparameters
        agent.n_steps = params.get("n_steps", 5)
        agent.gamma = params.get("gamma", 0.99)
        agent.lam = params.get("gae_lambda", 1.0)
        agent.ent_coef = params.get("ent_coef", 0.0)
        agent.value_coef = params.get("value_coef", 0.5)
        agent.max_grad_norm = params.get("max_grad_norm", 0.5)
        agent.lr = params.get("learning_rate", 7e-4)

        # Rebuild optimizer with new learning rate
        agent.optimizer = torch.optim.Adam(agent.model.parameters(), lr=agent.lr)

        print(f"\n{'='*80}")
        print(f"Training A2C with optimized hyperparameters")
        print(f"Curriculum stages: {len(curriculum)}")
        print(f"Total timesteps: {sum(stage['timesteps'] for stage in curriculum)}")
        print(f"{'='*80}\n")

        # Curriculum training loop
        stage_ckpts = []
        for i, stage in enumerate(curriculum):
            print(f"\n--- Stage {i+1}/{len(curriculum)} ---")
            print(f"  Horizon: {stage['horizon']}, Jobs: {stage['num_jobs']}, Timesteps: {stage['timesteps']}")

            env = make_env(
                seed=0,
                horizon=stage["horizon"],
                num_jobs=stage["num_jobs"],
                max_jobs=MAX_JOBS,
                lambda_1=lambda_1,
                lambda_2=lambda_2,
                lambda_3=lambda_3,
                idle_penalty=idle_penalty,
                invalid_penalty=invalid_penalty,
                use_potential_shaping=use_potential_shaping,
                shaping_gamma=shaping_gamma,
                randomize_instances=randomize_instances,
            )

            agent.env = env
            agent.train(total_timesteps=stage["timesteps"], plotter=plotter)

            # Per-stage checkpoint -- see the matching comment in
            # train_rl_agent.py for rationale.
            stage_ckpt = MODELS_DIR / f"a2c_{policy_type}_optimized_stage{i}_h{stage['horizon']}{path_suffix}.pt"
            torch.save(agent.model.state_dict(), stage_ckpt)
            print(f"  Saved stage checkpoint: {stage_ckpt}")
            stage_ckpts.append(stage_ckpt)

        # Save A2C model
        torch.save(agent.model.state_dict(), A2C_MODEL_PATH)
        print(f"\nA2C training complete. Model saved to: {A2C_MODEL_PATH}\n")

        extra_archive_files = []
        if use_rcpo:
            # lambda_history: (timestep, lambda_value, mean_episode_cost) tuples
            # logged at every slow-timescale multiplier update -- see
            # MaskableA2C.train() -- kept alongside the checkpoint so the
            # multiplier's convergence trajectory can be inspected/plotted
            # without rerunning training.
            lambda_history_path = MODELS_DIR / f"a2c_{policy_type}_lambda_history{path_suffix}.json"
            with open(lambda_history_path, "w") as f:
                json.dump(agent.lambda_history, f, indent=2)
            print(f"  Saved RCPO lambda history: {lambda_history_path}")
            extra_archive_files.append(lambda_history_path)

        # Archive this run's checkpoints under a dated/tagged folder so the
        # next run overwriting A2C_MODEL_PATH doesn't destroy this one -- see
        # Code/utils/results_log.py.
        archive_dir = archive_checkpoint_files(
            [A2C_MODEL_PATH, *stage_ckpts, ENV_CONFIG_PATH, *extra_archive_files],
            tag=run_tag,
        )
        print(f"Archived checkpoints to: {archive_dir}\n")

    plotter.close()
    print(f"Training reward plot saved to: {plot_run_dir}\n")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Train RL agent with Optuna-optimized hyperparameters"
    )
    parser.add_argument(
        "--algo",
        type=str,
        default="ppo",
        choices=["ppo", "a2c"],
        help="Algorithm to train"
    )
    parser.add_argument(
        "--policy-type",
        type=str,
        default="pointer",
        choices=["pointer", "flat"],
        help="A2C only: which architecture's best-params file to load and build.",
    )
    parser.add_argument(
        "--no-curriculum",
        action="store_true",
        help="Disable curriculum learning (single-stage training)"
    )
    parser.add_argument(
        "--stage4-timesteps",
        type=int,
        default=200_000,
        help="Timestep budget for the final curriculum stage (100 jobs, horizon=100)."
    )
    parser.add_argument(
        "--run-tag",
        type=str,
        default=None,
        help="Label for this run's archived checkpoints (rl_training/models/archive/). "
             "Defaults to '<algo>_<policy_type>_s4-<stage4_timesteps>[_<params-tag>]'."
    )
    parser.add_argument(
        "--params-tag",
        type=str,
        default=None,
        help="Load an alternative Optuna best-params file (e.g. 'tardiness', produced by "
             "optuna_tune.py --optimize-for tardiness) instead of the default reward-tuned "
             "one, and save checkpoints to a correspondingly-suffixed path so they don't "
             "overwrite the default model."
    )
    parser.add_argument(
        "--use-potential-shaping",
        action="store_true",
        help="Experiment 4: enable Solution 3 potential-based reward shaping (Ng, Harada, "
             "Russell 1999 -- see SchedulingEnv._compute_potential()). Off by default so "
             "it's A/B-able against the unshaped baseline. shaping_gamma is set to this "
             "run's own tuned 'gamma' hyperparameter."
    )
    parser.add_argument(
        "--randomize-instances",
        action="store_true",
        help="Experiment 2: draw a fresh random job set every episode instead of reusing "
             "the single fixed seed=0 instance every prior run trained/evaluated on -- see "
             "make_random_instance_resampler(). Optuna hyperparameters are NOT re-tuned "
             "for this distribution by this flag alone."
    )
    parser.add_argument(
        "--use-rcpo",
        action="store_true",
        help="Experiment 5: replace the fixed lambda_2 tardiness weight with a Lagrange "
             "multiplier adapted during training toward a tardiness constraint (Tessler, "
             "Mankowitz, Mannor, ICLR 2019, arXiv:1805.11074). A2C only. See "
             "Future/research/2026-08-21-rcpo-constrained-tardiness.md."
    )
    parser.add_argument(
        "--rcpo-alpha",
        type=float,
        default=0.0,
        help="RCPO constraint threshold on E[C(tau)] (weighted normalised tardiness "
             "per episode). Default 0.0 -- see the dated doc's Section 2 for why this "
             "doesn't require literally-zero tardiness to be achieved."
    )
    parser.add_argument(
        "--rcpo-lambda-lr",
        type=float,
        default=0.01,
        help="Step size for the multiplier's projected-ascent update."
    )
    parser.add_argument(
        "--rcpo-lambda-max",
        type=float,
        default=50.0,
        help="Upper projection bound for the multiplier (lower bound is always 0)."
    )
    parser.add_argument(
        "--rcpo-update-every",
        type=int,
        default=5,
        help="Number of completed episodes averaged into one multiplier update."
    )

    args = parser.parse_args()

    train_with_optimized_params(
        algorithm=args.algo,
        policy_type=args.policy_type,
        use_curriculum=not args.no_curriculum,
        stage4_timesteps=args.stage4_timesteps,
        run_tag=args.run_tag,
        params_tag=args.params_tag,
        use_potential_shaping=args.use_potential_shaping,
        randomize_instances=args.randomize_instances,
        use_rcpo=args.use_rcpo,
        rcpo_alpha=args.rcpo_alpha,
        rcpo_lambda_lr=args.rcpo_lambda_lr,
        rcpo_lambda_max=args.rcpo_lambda_max,
        rcpo_update_every=args.rcpo_update_every,
    )
